name: astral-sh/attest-action

description: A GitHub Action that generates PEP 740 publish attestations for your Python packages.

inputs:
  paths:
    description: One or more whitespace-separated directories or glob patterns to search for Python distributions to generate attestations for.
    required: false
    default: dist/*
  overwrite:
    description: Whether to overwrite existing attestations if they already exist.
    required: false
    default: "false"

outputs: {}

runs:
  using: composite
  steps:
    - name: setup uv
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
      with:
        version: ">=0.9.12"
        cache-dependency-glob: ${{ github.action_path }}/uv.lock

    - name: generate attestations
      run: |
        uv run --locked --project "${GITHUB_ACTION_PATH}" "${GITHUB_ACTION_PATH}/action.py"
      shell: bash
      env:
        ATTEST_ACTION_INPUT_PATHS: ${{ inputs.paths }}
        ATTEST_ACTION_INPUT_OVERWRITE: ${{ inputs.overwrite }}
