[project]
name = "attest-action"
version = "0.0.6"
description = "A GitHub Action that generates [PEP 740] publish attestations for your Python packages."
readme = "README.md"
dependencies = [
    "prettytable>=3.18.0",
    "pypi-attestations>=0.0.30",
    "sigstore>=4.1.0",
]
requires-python = ">=3.12"
classifiers = [
    # This is a GitHub Action, not a PyPI package.
    "Private :: Do Not Upload",
]

[dependency-groups]
dev = [
    "inline-snapshot>=0.35.3",
    "pytest>=9.1.1",
    "requests>=2.34.2",
    "ruff>=0.16.0",
    "ty>=0.0.65",
]


[tool.uv]
exclude-newer = "P7D"
